Update to the latest Joda Time
Attempting to run a job that uses the AWS client raised this exception

java.lang.IllegalStateException: Joda-time 2.2 or later version is required, but found version: null
    at com.amazonaws.util.DateUtils.handleException(DateUtils.java:147)
    at com.amazonaws.util.DateUtils.parseRFC822Date(DateUtils.java:195)
    at com.amazonaws.services.s3.internal.ServiceUtils.parseRfc822Date(ServiceUtils.java:78)
    ...